# Generated by Django 6.1 on 2026-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('scientific_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nl_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('victory_points', models.PositiveSmallIntegerField()),
                ('lives_in_forest', models.IntegerField(blank=True, null=True)),
                ('lives_in_grasslands', models.IntegerField(blank=True, null=True)),
                ('lives_in_wetlands', models.IntegerField(blank=True, null=True)),
                ('nest_type', models.CharField(blank=True, max_length=4, null=True)),
                ('nest_capacity', models.PositiveSmallIntegerField()),
                ('wingspan', models.PositiveSmallIntegerField()),
                ('expansion', models.CharField(blank=True, max_length=2, null=True)),
                ('food_is_multiple_choice', models.IntegerField()),
                ('worms', models.PositiveSmallIntegerField()),
                ('grains', models.PositiveSmallIntegerField()),
                ('berries', models.PositiveSmallIntegerField()),
                ('fish', models.PositiveSmallIntegerField()),
                ('rats', models.PositiveSmallIntegerField()),
                ('wild', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'bird',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('power_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=2, null=True)),
                ('type', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'power',
            },
        ),
    ]
