# Generated by Django 6.1 on 2026-09-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={'managed': False},
        ),
    ]
