# Generated by Django 6.1 on 2026-09-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='scientific_name',
            field=models.TextField(default=''),
        ),
    ]
