# Generated by Django 6.1 on 2026-09-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_alter_bird_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'managed': False},
        ),
    ]
