# Generated by Django 6.1 on 2026-09-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_alter_power_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Power',
        ),
    ]
