# Generated by Django 6.1 on 2026-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_delete_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('power_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=2, null=True)),
                ('type', models.CharField(max_length=4, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'power',
                'managed': False,
            },
        ),
    ]
