# Generated by Django 6.1 on 2026-09-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_power'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={},
        ),
    ]
