# Generated by Django 6.1 on 2026-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_alter_bird_options_alter_power_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='berries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='expansion',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='fish',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='food_is_multiple_choice',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='bird',
            name='grains',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lives_in_forest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lives_in_grasslands',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lives_in_wetlands',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='nest_capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='nest_type',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='nl_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='rats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='victory_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='wild',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='wingspan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bird',
            name='worms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
