# Generated by Django 6.1 on 2026-09-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0007_alter_bird_berries_alter_bird_expansion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualization.power'),
        ),
    ]
